Repository truenas/scale-build, pull requests merged in 2022-11, with the labels that each got.

#354 NAS-118856 / 22.12 / remove incorrect headers package
  conf/build.manifest
Labels: backport-22.12-RC.1

#357 NAS-119071 / 23.10 / Set authentication method using truenas-set-authentication-method.py …
  truenas_install/__main__.py
Labels: backport-22.12

#361 NAS-119071 / 22.12 / Set authentication method using truenas-set-authentication-method.py … (by themylogin)
  truenas_install/__main__.py
Labels: backport-22.12.1
