Repository truenas/scale-build, pull requests merged in 2022-04, with the labels that each got.

#267 NAS-115606 / 22.12 / add rsync to depends in README.md
  README.md
Labels: jira, backport-22.02.1

#265 NAS-115585 / 22.12 / Use golang 1.17 for building k3s
  conf/build.manifest
Labels: jira

#270 NAS-115622 / 22.12 / Fix apt sources
  conf/sources.list
Labels: jira

#266 NAS-115605 / 22.12 / Fix ValueError crashes
  scale_build/config.py
Labels: jira, backport-22.02.1

#285 NAS-115801 / 22.12 / Try to persist uids and gids across builds
  conf/reference-files/etc/group
  conf/reference-files/etc/passwd
  scale_build/update_image.py
  scale_build/utils/paths.py
Labels: jira, backport-22.02.1

#286 NAS-113866 / 22.12 / `truenas-devel` metapackage
  conf/build.manifest
Labels: backport-22.02.1

#291 NAS-115932 / 22.02.1 / Branch out for 22.02.1
  conf/build.manifest
  conf/sources.list
Labels: WIP

#292 NAS-115939 / 22.12 / Upgrade debian packages pulled in by debootstrap
  conf/build.manifest
  scale_build/bootstrap/bootstrapdir.py
Labels: backport-22.02.1
