Repository truenas/scale-build, pull requests merged in 2022-08, with the labels that each got.

#323 NAS-117519 / 22.12 / Various improvements to builder
  .gitignore
  conf/build.manifest
  identities/.gitkeep
  scale_build/config.py
  scale_build/packages/git.py
  scale_build/packages/package.py
  scale_build/packages/utils.py
  scale_build/utils/manifest.py
  scale_build/utils/package.py
Labels: jira

#327 NAS-117620 / 22.12 / fix SCALE HA upgrades
  truenas_install/__main__.py
Labels: backport-22.02.4

#333 NAS-117779 / 22.12 / Enforce passwd/group specified reference files
  scale_build/bootstrap/bootstrapdir.py
  scale_build/update_image.py
  scale_build/utils/paths.py
Labels: jira

#332 NAS-117776 / 22.12 / Clean chroot mounts when making update image
  scale_build/update_image.py
Labels: jira

#330 NAS-117762 / 22.12 / Build with BlueFin with Samba 4.17
  conf/build.manifest
Labels: jira

#334 NAS-117840 / 22.12 / Remove customized nss-pam-ldap from build
  conf/build.manifest
Labels: jira, backport-22.02.4
