Repository truenas/scale-build, pull requests merged in 2022-05, with the labels that each got.

#296 NAS-115937 / 22.12 / Properly raise exception if some package fails to checkout
  scale_build/checkout.py
Labels: backport-22.02.2

#298 NAS-116170 / 22.12 / retry git commands on failure
  scale_build/packages/git.py
Labels: jira, backport-22.02.2

#301 NAS-116225 / 22.12 / Use custom `smartmontools`
  conf/build.manifest
Labels: skip jira status, backport-22.02.2
