Repository truenas/scale-build, pull requests merged in 2023-06, with the labels that each got.

#441 NAS-122255 / 22.12.4 / Allow installing SCALE on CORE-created boot pool without upgrading ex…
  truenas_install/__main__.py
Labels: backport-23.10, backport-22.12.3

#446 NAS-122389 / 23.10 / Use pull script for building openseachest
  conf/build.manifest
Labels: backport-22.12.4

#454 NAS-122517 / 23.10 / fix the build
  conf/build.manifest
Labels: jira
