Repository truenas/scale-build, pull requests merged in 2023-08, with the labels that each got.

#476 NAS-123340 / 24.04 / Refine branchout process
  scale_build/branch_out.py
Labels: jira, backport-23.10, pending QA

#477 NAS-123349 / 24.04 / Accomodate all cgroups versions when checking if a process is running…
  truenas_install/__main__.py
Labels: backport-23.10

#481 NAS-123489 / 24.04 / Update mirrors to point to bookworm/dragonfish
  conf/build.manifest
Labels: jira

#483 NAS-123615 / 24.04 / Fix makefile not able to setup virtualenv
  Makefile
Labels: jira, backport-23.10

#485 NAS-123630 / 24.04 / Check if pip supports break systeem packages flag
  Makefile
Labels: backport-23.10

#489 NAS-123734 / 22.12.4 / Bump pyyaml to 6.0.1 as CI is not liking 5.4.1
  requirements.txt
Labels: jira
