Repository truenas/scale-build, pull requests merged in 2023-05, with the labels that each got.

#406 NAS-121767 / 23.10 / bump build-epoch to force clean build
  conf/build.manifest
Labels: jira

#408 NAS-121753 / 23.10 / Precheck for S3 service
  conf/build.manifest
  truenas_install/__main__.py
Labels: backported, backport-22.12.3

#414 NAS-121809 / 23.10 / Fix infinite recursion
  truenas_install/__main__.py
Labels: jira, backport-22.12.3

#418 NAS-121741 / 23.10 / remove execute bit on dpkg binary
  scale_build/image/update.py
Labels: backport-22.12.3

#423 NAS-122113 / 23.10 / Initial ccache support
  conf/build.manifest
  scale_build/config.py
  scale_build/packages/build.py
  scale_build/packages/ccache.py
  scale_build/packages/overlay.py
  scale_build/packages/package.py
  scale_build/preflight.py
  scale_build/utils/manifest.py
  scale_build/utils/paths.py
Labels: jira

#436 NAS-122146 / 22.12.3 / Branch out for 22.12.3
  conf/build.manifest
Labels: jira
