Repository truenas/scale-build, pull requests merged in 2023-10, with the labels that each got.

#504 NAS-124479 / 24.04 / rsync home dir to new boot environment on upgrade
  truenas_install/__main__.py
Labels: jira, backport-23.10.0, backport-22.12.4.1, backport-23.10.1

#512 NAS-124646 / 24.04 / Fix upgrade path from Core to SCALE
  truenas_install/__main__.py
Labels: jira, backport-23.10.0, backport-23.10.1

#515 NAS-124675 / 24.04 / Fix make clean
  scale_build/clean.py
Labels: jira, backport-23.10.0, backport-23.10.1

#522 NAS-124717 / 24.04 / Bump build epoch as group/passwd files have been changed
  conf/build.manifest
Labels: jira, backport-23.10.1

#524 NAS-124789 / 24.04 / Add openssl as an explicit dependency for openzfs
  conf/build.manifest
Labels: jira

#525 NAS-124793 / 24.04 / Fix incremental jobs when build epoch is changed
  jenkins/Incremental-NoPublish
  jenkins/IncrementalBuild
Labels: jira

#528 NAS-124916 / 23.10.0.1 / update build.manifest for 23.10.0.1
  conf/build.manifest
Labels: jira
