Repository truenas/scale-build, pull requests merged in 2024-09, with the labels that each got.

#707 NAS-130974 / 24.04.2.1 / Branch out for 24.04.2.1
  conf/build.manifest
Labels: jira

#712 NAS-131125 / 24.10-RC.1 / Do not clone systemd journal on upgrade (by anodos325)
  truenas_install/fhs.py
Labels: backport-24.10.0

#714 NAS-131145 / 24.10-RC.1 / Branch out mirrors for 24.10-RC.1
  conf/build.manifest
Labels: jira

#715 NAS-131184 / 24.04.2.2 / branch for 24.04.2.2
  conf/build.manifest
Labels: jira-low

#716 NAS-131247 / 25.04 / fix code_name for fangtooth
  conf/build.manifest
Labels: jira-low

#717 NAS-131253 / 25.04 / Remove hostname and mailname from update file
  scale_build/image/mtree.py
Labels: jira, backport-24.10.0

#718 NAS-131253 / 24.10.0 / Remove hostname and mailname from update file (by anodos325)
  scale_build/image/mtree.py
Labels: backport-24.10-RC.1

#725 NAS-131338 / 25.04 / Bring in non-free firmware for debian backports
  conf/build.manifest
Labels: jira, backported, backport-24.10.0, backport-24.10-RC.1

#720 NAS-131234 / 25.04 / pull in latest firmware-linux package from bookworm backports
  conf/build.manifest
Labels: backported, backport-24.10.0

#721 NAS-131234 / 24.10.0 / pull in latest firmware-linux package from bookworm backports (by yocalebo)
  conf/build.manifest
Labels: backported, backport-24.10-RC.1

#729 NAS-131346 / 25.04 / fix master build
  conf/build.manifest
Labels: jira-high

#730 NAS-131352 / 25.04 / Add explicit openssl dependency for swagger
  conf/build.manifest
Labels: jira

#731 NAS-130523 / 25.04 / Add incus-agent
  conf/build.manifest
Labels: skip jira status

#732 NAS-131376 / 24.04.2.3 / branch for 24.04.2.3
  conf/build.manifest
Labels: jira

#733 NAS-131449 / 25.04 / fix bug in deprecated service detection
  truenas_install/__main__.py
Labels: backport-24.10.0, backport-24.10-RC.1
