Repository truenas/scale-build, pull requests merged in 2024-02, with the labels that each got.

#580 NAS-127121 / 24.10 / Address CVE-2023-6246
  conf/build.manifest
Labels: backport-24.04

#582 NAS-127218 / 23.10.2 / branch for 23.10.2
  conf/build.manifest
Labels: jira

#583 NAS-127219 / 23.10.3 / bump _VERS to 23.10.3-MASTER
  scale_build/config.py
Labels: jira

#587 NAS-127325 / 24.04-RC.1 / Properly cleanup old manifest from the cloned `/data` directory
  truenas_install/__main__.py
Labels: backport-24.10

#595 NAS-127301 / 24.10 / add codename to manifest.json
  scale_build/packages/build.py
Labels: backport-24.04-RC.1
