Repository truenas/scale-build, pull requests merged in 2024-01, with the labels that each got.

#551 NAS-126052 / 24.04 / Add a debug statement to know if cached squashfs needs to be re-created
  scale_build/bootstrap/cache.py
Labels: jira

#554 NAS-125785 / 24.04 / Pull ssh packages from security mirror
  conf/build.manifest
Labels: pending QA

#557 NAS-126818 / 24.04 / Add builtin groups
  conf/reference-files/etc/group
Labels: jira

#558 NAS-126836 / None / Branch out repos for dragonfish
  conf/build.manifest
Labels: jira

#561 NAS-126844 / 24.10 / Bump version name in build manifest
  conf/build.manifest
Labels: jira

#570 NAS-127017 / 23.10.2 / Copy logs on upgrade
  truenas_install/__main__.py
Labels: backport-24.10

#573 Explicitly add systemd-container to additional-packages list
  conf/build.manifest
Labels: backport-24.04-RC.1

#576 NAS-127122 / 24.10 / Preserve nvram files of vms across scale upgrades
  truenas_install/__main__.py
Labels: jira, backport-23.10.2, backport-24.04-RC.1

#579 NAS-127126 / 24.10 / Fix conditional checking for nvram directory existence in old BE
  truenas_install/__main__.py
Labels: jira
