Repository truenas/scale-build, pull requests merged in 2024-04, with the labels that each got.

#608 NAS-128110 / 24.10 / Add increased network timeout for yarn install.
  conf/build.manifest
Labels: jira

#612 NAS-128104 / 24.10 / Bring in util-linux from security repo
  conf/build.manifest
Labels: backport-24.04

#609 NAS-127880 / 24.10 / Make sure we copy over netdata state from previous BE to new BE
  truenas_install/__main__.py
Labels: backport-24.04

#615 NAS-128206 / 24.04.0 / Branch out repos for 24.04.0
  conf/build.manifest
Labels: jira

#618 NAS-128355 / 24.10 / Write `/data/post-install.json`
  truenas_install/__main__.py
Labels: jira

#624 NAS-128548 / 24.10 / bump epoch since apt cdn urls changed
  conf/build.manifest
Labels: backport-24.04.1, jira, jira-low

#623 NAS-128497 / 24.10 / remove unmaintained chelsiouwire
  conf/build.manifest
Labels: backport-24.04.1

#620 NAS-128572 / 24.10 / Add gitlog
  scripts/gitlog.py
Labels: backport-24.04.1, jira

#626 NAS-128564 / 24.10 / Add truenas/sssd to SCALE build
  conf/build.manifest
  conf/reference-files/etc/group
  conf/reference-files/etc/passwd
Labels: jira
