Repository truenas/scale-build, pull requests merged in 2024-07, with the labels that each got.

#663 NAS-129991 / 24.10 / Fix setting posixacl on logs dataset
  truenas_install/__main__.py
  truenas_install/fhs.py
Labels: backport-24.04.2

#667 NAS-129876 / 24.10 / Add docker mirror to build manifest
  conf/build.manifest
Labels: skip jira status

#668 NAS-130165 / 24.10 / Update build to use Samba 4.20
  conf/build.manifest
Labels: jira

#674 NAS-130358 / 24.10 / Update apt preferences to fix build
  conf/build.manifest
Labels: jira
