Repository truenas/scale-build, pull requests merged in 2024-11, with the labels that each got.

#753 NAS-132360 / 24.04.2.5 / branch for 24.04.2.5
  conf/build.manifest
Labels: jira-low

#752 NAS-132358 / 24.10.0.2 / branch for 24.10.0.2
  conf/build.manifest
Labels: jira-low

#754 NAS-132446 / 25.04 / Initial add of option to use internal APT repo for builds
  conf/build.manifest
  scale_build/bootstrap/bootstrapdir.py
  scale_build/bootstrap/hash.py
  scale_build/config.py
  scale_build/image/iso.py
  scale_build/image/update.py
  scale_build/utils/manifest.py
Labels: jira-low, backport-24.10.1

#758 NAS-132519 / 25.04 / Nvidia rootfs overlay that will be loaded using systemd-sysext
  Makefile
  scale_build/extensions.py
  scale_build/main.py
Labels: jira

#761 NAS-132571 / 25.04 / Internal apt mirror support
  conf/build.manifest
  scale_build/bootstrap/bootstrapdir.py
  scale_build/bootstrap/hash.py
  scale_build/config.py
  scale_build/image/iso.py
  scale_build/image/update.py
  scale_build/utils/manifest.py
Labels: jira

#763 NAS-132673 / 24.10.1 / branch for 24.10.1
  conf/build.manifest
Labels: jira-low

#764 NAS-132674 / 24.10.2 / bump _VERS to 24.10.2-MASTER
  scale_build/config.py
Labels: jira-low

#762 NAS-132596 / 25.04 / Move nvidia extension to the rootfs image
  Makefile
  conf/build.manifest
  scale_build/extensions.py
  scale_build/image/bootstrap.py
  scale_build/image/manifest.py
  scale_build/image/update.py
  scale_build/image/utils.py
  scale_build/main.py
  scale_build/utils/kernel.py
  scale_build/utils/manifest.py
Labels: jira, backport-24.10.2

#767 NAS-132596 / 24.10.2 / Move nvidia extension to the rootfs image (by themylogin)
  Makefile
  conf/build.manifest
  scale_build/extensions.py
  scale_build/image/bootstrap.py
  scale_build/image/manifest.py
  scale_build/image/update.py
  scale_build/image/utils.py
  scale_build/main.py
  scale_build/utils/kernel.py
  scale_build/utils/manifest.py
Labels: backport-24.10.1

#772 NAS-132388 / 25.04 / Save snmp config directory in upgrades
  truenas_install/__main__.py
Labels: backport-24.10.1, backport-24.10.2

#775 NAS-132744 / 25.04 / Pull latest python3.11 from https://salsa.debian.org
  conf/build.manifest
Labels: backport-24.10.1, backport-24.10.2
