Repository truenas/scale-build, pull requests merged in 2024-10, with the labels that each got.

#736 NAS-131566 / 24.10-RC.2 / branch for 24.10-RC.2
  conf/build.manifest
Labels: jira

#739 NAS-131734 / 24.10.0 / branch for 24.10.0
  conf/build.manifest
Labels: jira

#740 NAS-131735 / 24.10.1 / bump to 24.10.1-MASTER
  scale_build/config.py
Labels: jira

#741 NAS-131773 / 25.04 / Fix unsquashfs error reporting
  truenas_install/__main__.py
Labels: jira, backport-24.10.0, backport-24.10.1

#747 NAS-132133 / 24.10.0.1 / branch for 24.10.0.1
  conf/build.manifest
Labels: jira-high
