Repository truenas/scale-build, pull requests merged in 2024-08, with the labels that each got.

#673 NAS-130350 / 24.10 / Remove nslcd package from build
  conf/build.manifest
Labels: jira

#677 NAS-130395 / 24.10 / Add nscd to base build
  conf/build.manifest
Labels: jira

#659 NAS-130445 / 24.10 / Generate mtree of some critical datasets
  scale_build/image/manifest.py
  scale_build/image/mtree.py
  scale_build/image/update.py
Labels: jira

#680 NAS-130560 / 24.10 / Branch out stable branch for EE
  conf/build.manifest
Labels: jira

#681 NAS-130561 / 24.10 / Update manifest to point to fangtooth
  conf/build.manifest
  scale_build/config.py
Labels: jira

#682 NAS-130563 / 24.10 / Branch out for BETA.1 EE
  conf/build.manifest
Labels: jira

#658 NAS-130564 / 25.04 / Remove unused definition of `install_requires` in `setup.py`
  setup.py
Labels: jira

#684 NAS-130569 / 25.04 / Shift mirrors to fangtooth
  conf/build.manifest
Labels: jira

#683 NAS-130342 / 25.04 / Remove nvidia drivers
  conf/build.manifest
  scale_build/packages/git.py
  scale_build/utils/manifest.py
Labels: backport-24.10

#686 NAS-130342 / 24.10-RC.1 / Remove nvidia drivers (by themylogin)
  conf/build.manifest
  scale_build/packages/git.py
  scale_build/utils/manifest.py
Labels: backported, backport-24.10-BETA.1

#689 NAS-130581 / 25.04 / Fix upgrades when we have apps running
  truenas_install/__main__.py
Labels: jira, backport-24.10-BETA.1, backport-24.10-RC.1

#688 NAS-130580 / 25.04 / Specify libarchive-tools is required to build SCALE
  README.md
Labels: jira

#696 TEN-1474 Option added to prevent deletion of ISO files during Make
  scale_build/config.py
  scale_build/image/iso.py
Labels: backport-24.10-BETA.1, backport-24.10-RC.1

#701 NAS-130832 / 25.04 / Preserve the syslog-ng.persist file on upgrades
  truenas_install/__main__.py
  truenas_install/fhs.py
Labels: backport-24.10-RC.1

#703 NAS-130881 / 25.04 / Do not use pending uploaded database on the new system
  truenas_install/__main__.py
Labels: jira, backport-24.10-RC.1

#705 NAS-130590 / 25.04 / Create Debian package that verifies integrity of file system
  conf/build.manifest
Labels: backport-24.10-RC.1
