Repository truenas/scale-build, pull requests merged in 2024-03, with the labels that each got.

#604 NAS-127740 / 24.10 / Pin bookworm-security for node-related packages
  conf/build.manifest
Labels: jira, backport-24.04

#600 NAS-127625 / 24.10 / Perform database migration right in installer
  truenas_install/__main__.py
Labels: skip jira status

#605 NAS-127858 / 24.10 / Remove legacy BSD-related code
  truenas_install/__main__.py
Labels: jira

#607 NAS-128069 / 24.10 / Update python-netsnmpagent library
  conf/build.manifest
Labels: jira
