Repository truenas/scale-build, pull requests merged in 2024-12, with the labels that each got.

#778 NAS-132837 / 24.10.2 / Fix kernel not using our custom python
  conf/build.manifest
Labels: jira, backport-24.10.1, backport-25.04

#781 NAS-132926 / 25.04 / python3 is a dependency for ipaclient
  conf/build.manifest
Labels: jira, backport-24.10.1, backport-24.10.2

#785 NAS-132944 / 25.04 / Add auditd to build manifest
  conf/build.manifest
Labels: jira

#786 NAS-132949 / 25.04 / go back to sha1 for manifest files
  scale_build/image/manifest.py
Labels: jira-high

#787 NAS-132964 / 25.04 / Add audit rules to build
  conf/build.manifest
  scale_build/image/mtree.py
  scale_build/image/update.py
Labels: jira

#789 NAS-132966 / 25.04 / Always add python3 as an explicit dependency
  conf/build.manifest
  scale_build/packages/package.py
Labels: jira-high

#791 NAS-132987 / 25.04 / bump epoch to force clean builds
  conf/build.manifest
Labels: jira-low

#790 NAS-132983 / 25.04 / Add prefix argument to privileged audit rules
  scale_build/image/update.py
Labels: jira

#792 NAS-133067 / 25.04 / Install all apt packages in a single transaction to improve the perfo…
  scale_build/image/update.py
Labels: jira

#793 NAS-133095 / 25.04 / Get build to work again after apt mirror updates
  conf/build.manifest
Labels: jira

#794 NAS-132923 / 25.04 / Build `dev-tools` extension
  README.md
  scale_build/extensions.py
  scale_build/image/bootstrap.py
  scale_build/image/update.py
  scale_build/update_image.py
Labels: skip jira status, backport-24.10.2

#796 NAS-133293 / 25.04 / remove psutil from truenas_install
  requirements.txt
  scale_build/utils/system.py
  setup.py
  truenas_install/__main__.py
  truenas_install/utils.py
Labels: jira-low
