Repository truenas/scale-build, pull requests merged in 2025-01, with the labels that each got.

#797 NAS-133413 / 25.04 / Fix `.squashfs` files not being cleaned up
  scale_build/image/update.py
Labels: backport-24.10.2

#800 NAS-133530 / 24.10.2 / bump version to 24.10.3-MASTER
  scale_build/config.py
Labels: jira-low

#801 NAS-133535 / 25.04 / Handle audit plugin changes
  scale_build/image/update.py
Labels: jira

#805 NAS-133575 / 25.04 / bump nvidia driver version
  conf/build.manifest
Labels: jira-high

#807 NAS-133580 / 25.04 / fix nvidia driver URL
  scale_build/extensions.py
Labels: jira-high, backport-24.10.2

#809 NAS-133632 / 25.04 / Update Samba to 4.21
  conf/build.manifest
Labels: jira-high

#810 NAS-133696 / 25.04 / Update scst from truenas-3.9.0-pre to truenas-3.10.0-pre
  conf/build.manifest
Labels: jira-low

#813 NAS-133784 / 25.04 / create stable/fangtooth repo
  conf/build.manifest
Labels: jira-low

#815 Change master build to 25.10 and name it Goldeye
  conf/build.manifest
  scale_build/config.py
Labels: jira-low

#817 NAS-133789 / 25.04 / branch for 25.04-BETA.1
  conf/build.manifest
Labels: jira-low

#818 NAS-133794 / 25.04-BETA.1 / Update apt mirrors for 25.04 BETA.1
  conf/build.manifest
Labels: jira

#812 NAS-133889 / 25.10 / Add usbutils
  conf/build.manifest
Labels: jira-low, backport-25.04-RC.1
