Repository truenas/scale-build, pull requests merged in 2025-05, with the labels that each got.

#849 NAS-135649 / 25.04.1 / branch for 25.04.1
  conf/build.manifest
Labels: jira-high

#850 NAS-135650 / 25.04.2 / bump version to 25.04.2-MASTER
  scale_build/config.py
Labels: jira-low

#851 NAS-135721 / 25.04.1 / Update apt mirrors for 25.04.1
  conf/build.manifest
Labels: jira-low

#855 NAS-135830 / 25.10 / add etc/security/limits.conf to exclude in mtree
  scale_build/image/mtree.py
Labels: backport-25.04.2, jira-low

#857 NAS-135854 / 25.10 / Add python version check to truenas_install module
  .github/workflows/manifest.yml
  truenas_install/__main__.py
Labels: jira-medium, backport-25.04.2, backport-25.04.1

#863 NAS-135905 / 25.10 / add truenas_pylibzfs to build
  conf/build.manifest
Labels: jira-low
