Repository truenas/scale-build, pull requests merged in 2025-02, with the labels that each got.

#825 NAS-132120 / 25.10 / Add nfs-utils package to base install
  conf/build.manifest
Labels: backport-25.04-RC.1

#823 NAS-133958 / 25.10 / Remove legacy VM usages from build
  conf/reference-files/etc/group
  conf/reference-files/etc/passwd
  truenas_install/__main__.py
Labels: backport-25.04-RC.1

#828 NAS-134219 / 25.10 / Remove 744 mode set on /var/lib/incus. Use the Debian default of 755.
  truenas_install/fhs.py
Labels: jira, backport-25.04-RC.1

#788 NAS-133071 / 25.04 / Add SCST-related packages to base install
  conf/build.manifest
Labels: jira-low

#824 NAS-133968 / 25.10 / Update mtree to better support cryptographic verification for STIG
  scale_build/image/mtree.py
Labels: backport-25.04-RC.1

#831 NAS-134367 / 25.04-RC.1 / branch out for 25.04-RC.1
  conf/build.manifest
Labels: jira-low
