Repository truenas/scale-build, pull requests merged in 2025-09, with the labels that each got.

#913 NAS-137350 / 26.04 / Fix GRUB upgrade for systems missing BIOS partition with variable EFI
  truenas_install/__main__.py
Labels: backport-25.10-RC.1

#915 NAS-137412 / 25.04.2.4 / Branch for 25.04.2.4
  conf/build.manifest
Labels: jira-high

#924 NAS-137541 / 26.04 / Add truenas-pwenc to build
  conf/build.manifest
Labels: jira-medium

#926 NAS-137645 / 26.04 / Fix updating from 25.10
  truenas_install/__main__.py
Labels: jira-high

#932 NAS-137690 / 26.04 / Add truenas_scram library to build
  conf/build.manifest
Labels: jira-medium
