Repository truenas/scale-build, pull requests merged in 2025-03, with the labels that each got.

#833 NAS-134872 / 25.10 / Add truenas_crypto_utils to build
  conf/build.manifest
Labels: jira

#838 NAS-135025 / 25.10 / Add TNC utils repo to build
  conf/build.manifest
Labels: jira-medium

#839 NAS-135050 / 24.10.2.1 / branch for 24.10.2.1
  conf/build.manifest
Labels: jira-high
