Repository truenas/scale-build, pull requests merged in 2025-04, with the labels that each got.

#840 NAS-135310 / 25.10 / Fix installer DNS
  conf/build.manifest
  scale_build/image/iso.py
Labels: jira-medium

#841 NAS-135369 / 25.10 / Fail on FreeBSD before trying to import anything
  truenas_install/__main__.py
Labels: jira-medium, pending QA, backport-25.04.1

#845 NAS-135494 / 24.10.2.2 / branch for 24.10.2.2
  conf/build.manifest
Labels: jira-low

#846 NAS-135571 / 25.10 / Allow specifying secret_env for packages as env variables
  scale_build/config.py
  scale_build/utils/manifest.py
Labels: jira-medium

#847 NAS-135642 / 25.10 / ignore nfs and sub{u/g}id files in mtree
  scale_build/image/mtree.py
Labels: jira-medium, backport-25.04.1
