Repository truenas/scale-build, pull requests merged in 2025-06, with the labels that each got.

#867 NAS-136176 / 25.10 / Various fixes after upgrading GE mirrors
  conf/build.manifest
Labels: no-time-tracked

#869 NAS-136185 / 25.10 / bump nvidia to latest stable 570 driver
  conf/build.manifest
Labels: jira-low

#872 NAS-136140 / 25.10 / Maintain logs across upgrades
  truenas_install/__main__.py
Labels: backport-25.04.2

#878 NAS-136421 / 25.04.2 / Revert "Remove legacy VM usages from build"
  conf/reference-files/etc/group
  conf/reference-files/etc/passwd
  truenas_install/__main__.py
Labels: jira-high, backport-25.10

#879 NAS-136421 / 25.10 / Revert "Remove legacy VM usages from build" (by Qubad786)
  conf/reference-files/etc/group
  conf/reference-files/etc/passwd
  truenas_install/__main__.py
Labels: skip jira status

#881 NAS-136436 / 25.10 / Bump tmpfs size to fix SIGBUS
  scale_build/image/bootstrap.py
Labels: jira-medium

#883 NAS-136455 / 25.10 / Bring in Samba 4.22
  conf/build.manifest
Labels: jira-medium
